branches:
  only:
    - master
    - /^v0.*$/
language: python
notifications:
  irc: chat.freenode.net#dedupe
python:
  - '3.4'
install: pip install -r requirements.txt
after_success: coveralls
sudo: false
addons:
  postgresql: '9.4'
services:
  - redis-server
before_script:
  - cp tests/test_config.py.travis tests/test_config.py
  - cp api/app_config.py.travis api/app_config.py
script: nosetests -v tests
before_deploy:
  - zip -r dedupeapi-latest.zip .
  - mkdir -p dpl_cd_upload
  - mv dedupeapi-latest.zip dpl_cd_upload/dedupeapi-latest.zip
deploy:
  provider: codedeploy
  access_key_id: AKIAIDJFUA6FY4AKAJ6Q
  secret_access_key:
    secure: L2IWMzEQu1h7QXqc6s4V0S75HyohzEyhpMweFG0frZRpK0RLMVLJiQrHWb4irHJgb/v3YTGCbj4k/t1apmK83JBdclvRHOIWG0y2Yi3Yt4TGdciI1Hkiughsr+LzK/+xYEG9lby3HF9phGmxLx8qVwQokAqZKkaqwcWKIqQGuMI=
  bucket: datamade-codedeploy
  revision_type: github
  application: dedupe-api
  deployment_group: dedupe-api-group
  on:
    tags: true
