branches: 
only:
- master
language: python
notifications: 
email: 
on_success: change
on_failure: always
irc: chat.freenode.net#dedupe
python:
- '3.4'
install: pip install -r requirements.txt
after_success: coveralls
sudo: false
addons:
  postgresql: '9.4'
services:
- redis-server
before_script:
- cp tests/test_config.py.travis tests/test_config.py
- cp api/app_config.py.travis api/app_config.py
script: nosetests --with-coverage --cover-package=api tests
deploy:
- provider: s3
  access_key_id: AKIAI46US37BJ27ZPPSQ
  secret_access_key: &1
    secure: Blyg4CVbH2y1C56VUnp17MRvm8ZVeudWX8fI0jpz7JyUBMRRA+ltIjI2qvs6EjUVyEfLXoryHjOAsqrghPyrGz83XKhex8cO+Bx+fKgl7vS9Vw2CMTCYUKrwjsxooKuI9n1caItMW5GmnonVPusY3Cu8dsnFN0j86N/PxYd+s84=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: datamade/dedupe-api
  bucket: datamade-codedeploy
- provider: codedeploy
  access_key_id: AKIAI46US37BJ27ZPPSQ
  secret_access_key: *1
  bucket: datamade-codedeploy
  key: dedupeapi-latest.zip
  bundle_type: zip
  application: dedupe-api
  deployment_group: dedupe-api-group
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv dedupeapi-latest.zip dpl_cd_upload/dedupeapi-latest.zip
